# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 820d7b1ff4979b2a2d27142490fc6686e525c8bece6700dae4e396c19042d58434fc6cfe61d6e029f82dafab58a753ad9eb375905af913f288f44594f28e013b

test:
  secret_key_base: 74d604a7a8b54813c9596761d857227cdd5c6d94d93d38b707b1d86362c6d11d48e8f0156f517786544fa5b654b1f6dad8afd83c593810d698bc6a4a38d31c22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
    #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 01f5b9c9287c189f3d5bbd9d79e0b1595a9a97423c5a7b0997d60aefeeb73c5396de768fbd08f2dbae6bfeed968ade1f64d989eb9125f852648ba8c64ac47f1
